base_link: '/base_footprint'

# =====================================================
right:
    end_effector_name: 'gripper'  #ee group name

    #actuated joints in end effector
    joints : ['gripper_left_finger_joint', 'gripper_right_finger_joint']

    #open position
    pregrasp_posture : [0.05] #for sim
    pregrasp_time_from_start : 2.0

    #close position
    grasp_posture : [0.01] #for sim
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    #desired pose from end effector to grasp - [r, p, y] #1.5707 = PI/2
    grasp_pose_to_eef : [0.0, 0.0, 0.0]
    grasp_pose_to_eef_rotation : [0.0, 0.0, 3.14159]

    end_effector_parent_link: 'arm_tool_link'